# Site settings
title: '<<'
description: 'GDD 워크플로우 / 프레임워크'

# Build settings
markdown: kramdown

# Theme (GitHub Pages default)
theme: jekyll-theme-minima

# Exclude files from processing
exclude:
  - .git
  - .github
  - README.md
